using Microsoft.AspNetCore.Mvc;
using Manager.Models;

namespace Manager.Controllers
{
    public class Registration : Controller
    {
        public IActionResult nRegistrations()
        {
            var registrations = new List<RegistrationVM>
{
    new RegistrationVM
    {
        RegistrationID = 1,
        RoomID = "R101",
        RoomName = "Lab A",
        BuildingID = "B01",
        BuildingName = "IT Building",
        StudentID = "S001",
        StudentName = "Nguyen Van A",
        Semester = "Fall",
        AcademicYear = 2024,
        ApplicationStatus = "Approved",
        ClassID = "C01",
        ClassName = "Computer Science",
        CourseID = "CS101",
        CourseName = "Introduction to Programming",
        FacultyID = "F01",
        FacultyName = "Information Technology",
        BirthDate = new DateTime(2002, 5, 20),
        Gender = true,
        PhoneNumber = "0123456789",
        Email = "nguyenvana@example.com",
        ProvinceID = 1,
        ProvinceName = "Hanoi",
        District = "Hoan Kiem",
        Ward = "Trang Tien",
        Street = "Le Thanh Tong",
        IDCard = "012345678",
        IsLeader = false,
        Ethnicity = "Kinh",
        Religion = "None",
        Nationality = "Vietnamese",
        DateOfIssueOfIDCard = new DateTime(2020, 6, 10),
        PlaceOfIssueOfIDCard = "Hanoi",
        PolicyCoverage = "None",
        InsuranceNumber = "123456789",
        NgayCapBHXH = new DateTime(2021, 3, 5),
        GiaTriSuDungTuNgay = new DateTime(2021, 3, 6),
        ThoiDiem5NamLienTuc = new DateTime(2026, 3, 6),
        IDTinhCapBHXH = 1,
        TenTinhCapBHXH = "Hanoi",
        KhamBenhBanDau = "Hanoi Hospital",
        AnhThe4x6 = "photo1.png",
        AnhCMNDMatTruoc = "cmnd_front_1.png",
        AnhCMNDMatSau = "cmnd_back_1.png",
        AnhBHYTMatTruoc = "bhyt_front_1.png",
        RelativeID = 1,
        RelativeName = "Nguyen Van B",
        RelativePhoneNumber = "0987654321",
        RelativeAddress = "Hanoi, Vietnam"
    },
    new RegistrationVM
    {
        RegistrationID = 2,
        RoomID = "R202",
        RoomName = "Room 202",
        BuildingID = "B02",
        BuildingName = "Science Building",
        StudentID = "S002",
        StudentName = "Tran Thi B",
        Semester = "Spring",
        AcademicYear = 2025,
        ApplicationStatus = "Pending",
        ClassID = "C02",
        ClassName = "Mathematics",
        CourseID = "MATH201",
        CourseName = "Linear Algebra",
        FacultyID = "F02",
        FacultyName = "Mathematics",
        BirthDate = new DateTime(2001, 8, 15),
        Gender = false,
        PhoneNumber = "0987123456",
        Email = "tranthib@example.com",
        ProvinceID = 2,
        ProvinceName = "Ho Chi Minh City",
        District = "District 1",
        Ward = "Ben Nghe",
        Street = "Nguyen Hue",
        IDCard = "987654321",
        IsLeader = true,
        Ethnicity = "Kinh",
        Religion = "None",
        Nationality = "Vietnamese",
        DateOfIssueOfIDCard = new DateTime(2019, 9, 1),
        PlaceOfIssueOfIDCard = "Ho Chi Minh City",
        PolicyCoverage = "Scholarship",
        InsuranceNumber = "987654321",
        NgayCapBHXH = new DateTime(2020, 10, 5),
        GiaTriSuDungTuNgay = new DateTime(2020, 10, 6),
        ThoiDiem5NamLienTuc = new DateTime(2025, 10, 6),
        IDTinhCapBHXH = 2,
        TenTinhCapBHXH = "Ho Chi Minh City",
        KhamBenhBanDau = "HCM Hospital",
        AnhThe4x6 = "photo2.png",
        AnhCMNDMatTruoc = "cmnd_front_2.png",
        AnhCMNDMatSau = "cmnd_back_2.png",
        AnhBHYTMatTruoc = "bhyt_front_2.png",
        RelativeID = 2,
        RelativeName = "Tran Thi C",
        RelativePhoneNumber = "0934567890",
        RelativeAddress = "Ho Chi Minh City, Vietnam"
    },
    new RegistrationVM
    {
        RegistrationID = 3,
        RoomID = "R303",
        RoomName = "Physics Lab",
        BuildingID = "B03",
        BuildingName = "Science Complex",
        StudentID = "S003",
        StudentName = "Le Quoc C",
        Semester = "Summer",
        AcademicYear = 2025,
        ApplicationStatus = "Rejected",
        ClassID = "C03",
        ClassName = "Physics",
        CourseID = "PHY101",
        CourseName = "Mechanics",
        FacultyID = "F03",
        FacultyName = "Physics",
        BirthDate = new DateTime(2003, 11, 30),
        Gender = true,
        PhoneNumber = "0909123456",
        Email = "lequocc@example.com",
        ProvinceID = 3,
        ProvinceName = "Da Nang",
        District = "Hai Chau",
        Ward = "Thuan Phuoc",
        Street = "Bach Dang",
        IDCard = "456789123",
        IsLeader = false,
        Ethnicity = "Kinh",
        Religion = "Buddhism",
        Nationality = "Vietnamese",
        DateOfIssueOfIDCard = new DateTime(2021, 7, 12),
        PlaceOfIssueOfIDCard = "Da Nang",
        PolicyCoverage = "Underprivileged",
        InsuranceNumber = "456789123",
        NgayCapBHXH = new DateTime(2021, 9, 20),
        GiaTriSuDungTuNgay = new DateTime(2021, 9, 21),
        ThoiDiem5NamLienTuc = new DateTime(2026, 9, 21),
        IDTinhCapBHXH = 3,
        TenTinhCapBHXH = "Da Nang",
        KhamBenhBanDau = "Da Nang Hospital",
        AnhThe4x6 = "photo3.png",
        AnhCMNDMatTruoc = "cmnd_front_3.png",
        AnhCMNDMatSau = "cmnd_back_3.png",
        AnhBHYTMatTruoc = "bhyt_front_3.png",
        RelativeID = 3,
        RelativeName = "Le Thi D",
        RelativePhoneNumber = "0912345678",
        RelativeAddress = "Da Nang, Vietnam"
    }
};
            return View(registrations);
        }
        public IActionResult Registrations()
        {
            var registrations = new List<RegistrationVM>
{
    new RegistrationVM
    {
        RegistrationID = 1,
        RoomID = "R101",
        RoomName = "Lab A",
        BuildingID = "B01",
        BuildingName = "IT Building",
        StudentID = "S001",
        StudentName = "Nguyen Van A",
        Semester = "Fall",
        AcademicYear = 2024,
        ApplicationStatus = "Approved",
        ClassID = "C01",
        ClassName = "Computer Science",
        CourseID = "CS101",
        CourseName = "Introduction to Programming",
        FacultyID = "F01",
        FacultyName = "Information Technology",
        BirthDate = new DateTime(2002, 5, 20),
        Gender = true,
        PhoneNumber = "0123456789",
        Email = "nguyenvana@example.com",
        ProvinceID = 1,
        ProvinceName = "Hanoi",
        District = "Hoan Kiem",
        Ward = "Trang Tien",
        Street = "Le Thanh Tong",
        IDCard = "012345678",
        IsLeader = false,
        Ethnicity = "Kinh",
        Religion = "None",
        Nationality = "Vietnamese",
        DateOfIssueOfIDCard = new DateTime(2020, 6, 10),
        PlaceOfIssueOfIDCard = "Hanoi",
        PolicyCoverage = "None",
        InsuranceNumber = "123456789",
        NgayCapBHXH = new DateTime(2021, 3, 5),
        GiaTriSuDungTuNgay = new DateTime(2021, 3, 6),
        ThoiDiem5NamLienTuc = new DateTime(2026, 3, 6),
        IDTinhCapBHXH = 1,
        TenTinhCapBHXH = "Hanoi",
        KhamBenhBanDau = "Hanoi Hospital",
        AnhThe4x6 = "photo1.png",
        AnhCMNDMatTruoc = "cmnd_front_1.png",
        AnhCMNDMatSau = "cmnd_back_1.png",
        AnhBHYTMatTruoc = "bhyt_front_1.png",
        RelativeID = 1,
        RelativeName = "Nguyen Van B",
        RelativePhoneNumber = "0987654321",
        RelativeAddress = "Hanoi, Vietnam"
    },
    new RegistrationVM
    {
        RegistrationID = 2,
        RoomID = "R202",
        RoomName = "Room 202",
        BuildingID = "B02",
        BuildingName = "Science Building",
        StudentID = "S002",
        StudentName = "Tran Thi B",
        Semester = "Spring",
        AcademicYear = 2025,
        ApplicationStatus = "Pending",
        ClassID = "C02",
        ClassName = "Mathematics",
        CourseID = "MATH201",
        CourseName = "Linear Algebra",
        FacultyID = "F02",
        FacultyName = "Mathematics",
        BirthDate = new DateTime(2001, 8, 15),
        Gender = false,
        PhoneNumber = "0987123456",
        Email = "tranthib@example.com",
        ProvinceID = 2,
        ProvinceName = "Ho Chi Minh City",
        District = "District 1",
        Ward = "Ben Nghe",
        Street = "Nguyen Hue",
        IDCard = "987654321",
        IsLeader = true,
        Ethnicity = "Kinh",
        Religion = "None",
        Nationality = "Vietnamese",
        DateOfIssueOfIDCard = new DateTime(2019, 9, 1),
        PlaceOfIssueOfIDCard = "Ho Chi Minh City",
        PolicyCoverage = "Scholarship",
        InsuranceNumber = "987654321",
        NgayCapBHXH = new DateTime(2020, 10, 5),
        GiaTriSuDungTuNgay = new DateTime(2020, 10, 6),
        ThoiDiem5NamLienTuc = new DateTime(2025, 10, 6),
        IDTinhCapBHXH = 2,
        TenTinhCapBHXH = "Ho Chi Minh City",
        KhamBenhBanDau = "HCM Hospital",
        AnhThe4x6 = "photo2.png",
        AnhCMNDMatTruoc = "cmnd_front_2.png",
        AnhCMNDMatSau = "cmnd_back_2.png",
        AnhBHYTMatTruoc = "bhyt_front_2.png",
        RelativeID = 2,
        RelativeName = "Tran Thi C",
        RelativePhoneNumber = "0934567890",
        RelativeAddress = "Ho Chi Minh City, Vietnam"
    },
    new RegistrationVM
    {
        RegistrationID = 3,
        RoomID = "R303",
        RoomName = "Physics Lab",
        BuildingID = "B03",
        BuildingName = "Science Complex",
        StudentID = "S003",
        StudentName = "Le Quoc C",
        Semester = "Summer",
        AcademicYear = 2025,
        ApplicationStatus = "Rejected",
        ClassID = "C03",
        ClassName = "Physics",
        CourseID = "PHY101",
        CourseName = "Mechanics",
        FacultyID = "F03",
        FacultyName = "Physics",
        BirthDate = new DateTime(2003, 11, 30),
        Gender = true,
        PhoneNumber = "0909123456",
        Email = "lequocc@example.com",
        ProvinceID = 3,
        ProvinceName = "Da Nang",
        District = "Hai Chau",
        Ward = "Thuan Phuoc",
        Street = "Bach Dang",
        IDCard = "456789123",
        IsLeader = false,
        Ethnicity = "Kinh",
        Religion = "Buddhism",
        Nationality = "Vietnamese",
        DateOfIssueOfIDCard = new DateTime(2021, 7, 12),
        PlaceOfIssueOfIDCard = "Da Nang",
        PolicyCoverage = "Underprivileged",
        InsuranceNumber = "456789123",
        NgayCapBHXH = new DateTime(2021, 9, 20),
        GiaTriSuDungTuNgay = new DateTime(2021, 9, 21),
        ThoiDiem5NamLienTuc = new DateTime(2026, 9, 21),
        IDTinhCapBHXH = 3,
        TenTinhCapBHXH = "Da Nang",
        KhamBenhBanDau = "Da Nang Hospital",
        AnhThe4x6 = "photo3.png",
        AnhCMNDMatTruoc = "cmnd_front_3.png",
        AnhCMNDMatSau = "cmnd_back_3.png",
        AnhBHYTMatTruoc = "bhyt_front_3.png",
        RelativeID = 3,
        RelativeName = "Le Thi D",
        RelativePhoneNumber = "0912345678",
        RelativeAddress = "Da Nang, Vietnam"
    }
};

            return View(registrations);
        }
        public IActionResult RegistrationDetail()
        {
            RegistrationVM registrationVM = new RegistrationVM
            {
                RegistrationID = 1,
                RoomID = "R101",
                RoomName = "Lab A",
                BuildingID = "B01",
                BuildingName = "IT Building",
                StudentID = "S001",
                StudentName = "Nguyen Van A",
                Semester = "Fall",
                AcademicYear = 2024,
                ApplicationStatus = "Approved",
                ClassID = "C01",
                ClassName = "Computer Science",
                CourseID = "CS101",
                CourseName = "Introduction to Programming",
                FacultyID = "F01",
                FacultyName = "Information Technology",
                BirthDate = new DateTime(2002, 5, 20),
                Gender = true,
                PhoneNumber = "0123456789",
                Email = "nguyenvana@example.com",
                ProvinceID = 1,
                ProvinceName = "Hanoi",
                District = "Hoan Kiem",
                Ward = "Trang Tien",
                Street = "Le Thanh Tong",
                IDCard = "012345678",
                IsLeader = false,
                Ethnicity = "Kinh",
                Religion = "None",
                Nationality = "Vietnamese",
                DateOfIssueOfIDCard = new DateTime(2020, 6, 10),
                PlaceOfIssueOfIDCard = "Hanoi",
                PolicyCoverage = "None",
                InsuranceNumber = "123456789",
                NgayCapBHXH = new DateTime(2021, 3, 5),
                GiaTriSuDungTuNgay = new DateTime(2021, 3, 6),
                ThoiDiem5NamLienTuc = new DateTime(2026, 3, 6),
                IDTinhCapBHXH = 1,
                TenTinhCapBHXH = "Hanoi",
                KhamBenhBanDau = "Hanoi Hospital",
                AnhThe4x6 = "photo1.png",
                AnhCMNDMatTruoc = "cmnd_front_1.png",
                AnhCMNDMatSau = "cmnd_back_1.png",
                AnhBHYTMatTruoc = "bhyt_front_1.png",
                RelativeID = 1,
                RelativeName = "Nguyen Van B",
                RelativePhoneNumber = "0987654321",
                RelativeAddress = "Hanoi, Vietnam"
            };
            return View(registrationVM);
        }
        public IActionResult AcceptRegistrations()
        {
            return View();
        }
        public IActionResult RejectRegistrations()
        {
            return View();
        }
    }
}
